version: "3"
services:
  db:
    image: postgres
    # volumes:
    #     - ./backup_data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432

  backend:
    build: ./backend
    # command: bash -c "python manage.py migrate && 
    #                   python manage.py runserver 0.0.0.0:8000"
    command: ["./wait-for-it.sh", "db:5432","--","python","manage.py","runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8000:8000
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - db
    ports:
      - 80:80
  
  # nginx_backend_server:
  #   build: ./nginx_backend_server
  #   ports:
  #       - 8000:8000
  #   depends_on:
  #       - database

